### ISSUE TITLE
Please release a new version.

### ISSUE THREAD

**Issue by jaybowong** [UrbanApps/UAProgressView#13]
I've been using the `HEAD` parameter in my Podfile for getting the fix in [e887eea](https://github.com/UrbanApps/UAProgressView/commit/e887eea2e2824bd762e4c38a456906d10d844fcd) for months to avoid flashing in `setProgress:animated`.

The last version was released on Jul 19. Please release a new version to include these fixes after Jul 19. Thanks.

**Comment by coneybeare** [comment]
Done. version 0.1.3 released

**Comment by jaybowong** [comment]
Thanks!
