### ISSUE TITLE
There is a warning.

### ISSUE THREAD

**Issue by shantj** [UrbanApps/UAProgressView#20]
- (void)animateToProgress:(CGFloat)progress {
  
  ......
  
  animation.delegate = self;      ( Assigning to 'id<CAAnimationDelegate> _Nullable' from incompatible type 'UAProgressView *const __strong')
  
  ......
  }

**Comment by GorbAnthony** [comment]
In the **UAProgressView.h** file, replace the string 
`@interface UAProgressView : UIView` 
by 
`@interface UAProgressView : UIView <CAAnimationDelegate>`

**Comment by coneybeare** [comment]
Please submit a pull request
