### ISSUE TITLE
Progress is flashing when setprogress:animated:YES

### ISSUE THREAD

**Issue by gtarashuk** [UrbanApps/UAProgressView#6]
Hey sir!
Thanks for great class!
The problem is when I`m setting progress animated it goes great but when animation is finished the progressview is flashing (from last progress to current) 
I think its in updating BezierPath

Can u help me pls?

TY 
Grigory

**Comment by SiarheiDrasvianski** [comment]
I have the same issue.
It can be reproduced also for sample project, but only on device (not simulator).
Great control anyway.
